Blog app - views
a-laarabi/Blog pull request #6
Opened 2022-11-04 05:50 UTC by a-laarabi

# What?
In this pull request :

- Use preprocessed HTML file with embedded Ruby code.
- Use layouts and templates for shared content.
- Implement the design from the sneak peek wireframes.

## Cheers and happy reviewing 🥇

2022-11-04 07:26 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @a-laarabi 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 07:26 UTC, tresorsawasawa commented on app/views/users/index.html.erb
> +</section>
- [x] Kindly make sure the index view page matches the expected [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_root_users.png) as required for the project, each element should be placed at his correct place.
### Here is your styling:
![Screenshot from 2022-11-04 08-45-27](https://user-images.githubusercontent.com/83042742/199910589-6d04b52e-aa04-401c-a038-713b79aa20b6.png)

2022-11-04 07:26 UTC, tresorsawasawa commented on app/views/users/show.html.erb
> +    </div>
- [ ] Kindly make sure you fix the overlapping profile image on each **[wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md)** to match the required design. Right now, the profile image on each wireframe makes your design not match the expected result.
You can see on the image of the previous comment.

2022-11-04 07:26 UTC, tresorsawasawa commented on app/views/posts/index.html.erb
> +</section>
- [ ] Kindly make sure the `app/views/posts/index.html.erb` page sticks as much as possible to its expected **[wireframe design](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_user_page.png)**

2022-11-05 11:31 UTC, arslanbisharat commented
Hi @a-laarabi,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-06 22:42 UTC, merged